=== himylxn/apuntes-DAW1/Lenguajes/Ejercicios/UD04-Validating XML documents/EjercicioCorregidos/EjerciciosXSD/bond_movies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="bond_movies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="movie" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string" />
                            <xs:element  name="bond" type="xs:string" />
                            <xs:element name="bond_girl" type="xs:string" />
                            <xs:element name="regie" type="xs:string" />
                            <xs:element name="year" type="xs:gYear" />
                            <xs:element name="duration" type="durationType"/>
                        </xs:sequence>
                        <xs:attribute name="number" use="required" type="numberType" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="month" type="monthType" use="required" />
            <xs:attribute name="year" type="xs:gYear" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="durationType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="300"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="numberType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="3"/>
            <xs:pattern value="_\d{2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="monthType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="January"/>
            <xs:enumeration value="February"/>
            <xs:enumeration value="March"/>
            <xs:enumeration value="April"/>
            <xs:enumeration value="May"/>
            <xs:enumeration value="June"/>
            <xs:enumeration value="July"/>
            <xs:enumeration value="August"/>
            <xs:enumeration value="September"/>
            <xs:enumeration value="October"/>
            <xs:enumeration value="November"/>
            <xs:enumeration value="December"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== himylxn/apuntes-DAW1/Lenguajes/Ejercicios/Unidad4/EjercicioCorregidos/EjerciciosXSD/Ejercicio20-XSD.xml
<bond_movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="bond_movies.xsd" month="August" year="2013">
    <movie number="_01">
        <title>Dr. No</title>
        <bond>Sean Connery</bond>
        <bond_girl>Ursula Andress</bond_girl>
        <regie>Terence Young</regie>
        <year>1962</year>
        <duration>105</duration>
    </movie>
    <movie number="_02">
        <title>From russia with love</title>
        <bond>Sean Connery</bond>
        <bond_girl>Daniela Bianchi</bond_girl>
        <regie>Terence Young</regie>
        <year>1963</year>
        <duration>110</duration>
    </movie>
    <movie number="_03">
        <title>Goldfinger</title>
        <bond>Sean Connery</bond>
        <bond_girl>Honor Blackman</bond_girl>
        <regie>Guy Hamilton</regie>
        <year>1964</year>
        <duration>106</duration>
    </movie>
    <movie number="_04">
        <title>Thunderball</title>
        <bond>Sean Connery</bond>
        <bond_girl>Claudine Auger</bond_girl>
        <regie>Terence Young</regie>
        <year>1965</year>
        <duration>125</duration>
    </movie>
</bond_movies>
