=== himylxn/apuntes-DAW1/Lenguajes/Ejercicios/UD04-Validating XML documents/EjercicioCorregidos/EjerciciosXSD/cards.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cards">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="card" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="initials">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-z] [a-z] [a-z]" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="age" type="xs:integer" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== himylxn/apuntes-DAW1/Lenguajes/Ejercicios/UD04-Validating XML documents/EjercicioCorregidos/EjerciciosXSD/Ejercicio25-XSD.xml
<cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="cards.xsd">
    <card>
        <name>Antonio Machado Ruiz</name>
        <initials>a m r</initials>
        <age>22</age>
    </card>
    <card>
        <name>Mario Moreno</name>
        <initials>m m o</initials>
        <age>23</age>
    </card>
    <card>
        <name>Ada Lovelace</name>
        <initials>a l o</initials>
        <age>24</age>
    </card>
    <card>
        <name>pablo ruiz picasso</name>
        <initials>p r p</initials>
        <age>24</age>
    </card>
</cards>
