<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE library [
    <!ELEMENT library (book,journal,misc)>
    <!ELEMENT book (title,editor,publisher)>
    <!ATTLIST book id NMTOKEN #REQUIRED>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT editor (#PCDATA)>
    <!ELEMENT publisher (#PCDATA)>
    <!ELEMENT journal (title,volume)>
    <!ATTLIST journal id NMTOKEN #REQUIRED>
    <!ATTLIST journal publ_year NMTOKEN #REQUIRED>
    <!ELEMENT volume (#PCDATA|number)*>
    <!ELEMENT number (#PCDATA)>
    <!ELEMENT misc (author,title,year,pages)>
    <!ATTLIST misc id NMTOKEN #REQUIRED>
    <!ATTLIST misc id2 NMTOKEN #REQUIRED>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT pages (#PCDATA)>
]>


<library>
    <book id="2003-Blanken">
        <title>Intelligent XML Search</title>
        <editor>Henk A. Blanken et al.</editor>
        <publisher>Springer Verlag</publisher>
    </book>

    <journal id="TODS_1_2003" publ_year="003">
        <title>ACM Transactions on Databases</title>
        <volume>24<number>1</number></volume>
    </journal>
    <misc id="Dipl2002-12" id2="4782784874">
        <author>U. Known</author>
        <title>The Diploma Thesis that didnâ€™t appear</title>
        <year>2002</year>
        <pages>0</pages>
    </misc>
</library> 